#--------------------------------------------------------------------------------
# Options can be set in config file or on the command line. Run
# `spikely cohort --help` for more detail.
# Order of precedence is:
# 1) first sample, gene, or variant specific values set in the config are used
#    and override all options below;
# 2) next options set on the command line are used to provide global defaults,
#    and override all options below;
# 3) next general options set in the config file are used to provide global
#    defaults, and override all options below;
# 4) lastly hard coded defaults set in code are used.
#--------------------------------------------------------------------------------

#--------------------------------------------------------------------------------
# General options and config level defaults.
#--------------------------------------------------------------------------------

# The heritability option takes a value from 0 to 1.  This value
# determines the probability that a given individual will have disease
# allele(s) in one of the genes represented in the disease VCF file.

heritability: 0.5

# One of recessive, dominant, de_novo, x-linke, additive
inheritance: dominant

# Maximum MAF for any single variant in the spiked VCF file.

max_rate: 0.005

# Maximum MAF (in population - as determined by the 'maf_key' in
# disease variants file) for a given variant.  Variant with a higher
# MAF will not be used for spiking.

max_maf: 0.0001

# Spikely uses information from the INFO column to determine the
# allele frequency of ALT alleles in diesease VCF file.  Setting
# af_key (defaults is AF) below determines what INFO tag is used to
# lookup the allele frequency. Sometimes these allele frequency
# estimates are missing and spikely will try to calculate the maximum
# allele frequency that could have been present in a population to
# have been present in the population but still not have been sampled.
# For this calculation spikely will use the an_key (default AN) to
# look up the allele number (number of alleles sampled for a site) and
# set the AF as 1/(AN+1).  If the allele number is also not available
# then spikely will use a default allele frequency that is specified
# in the config file using the default_af tag.  The idea of the value
# provided to the default_af option is that this would be an estimate
# of the value calculated from 1/(AN+1).  Finally if no allele
# frequency can be determined by any of the above methods then a
# default value of 0 is used for the allele frequency and this variant
# would be sampled less frequently (or more frequently for de novo)
# than any other allele.

af_key: AF
an_key: AN
default_af: 8.3e-6

# Sets the default 'population attributable risk percent' for any gene.

par: 0.3

# Key in disease VCF file INFO field that specifies name/id of the
# disease gene associated with each variant.

gene_id_key: GENEINFO

# Comma-separated list of sample IDs from samples VCF file to use as
# cases.  If not specifed assumes all samples in sample VCF file are
# cases.

case_ids: Case_01,Case_02,Case_03

#--------------------------------------------------------------------------------
# Sample specific options.  These over ride command line and config defaults.
#--------------------------------------------------------------------------------

# samples:
Case_01:
    inheritance: recessive

#--------------------------------------------------------------------------------
# Gene specific options.  These over ride command line and config defaults.
#--------------------------------------------------------------------------------
genes:
  KRIT1:
    par: 0.59
  CCM2:
    par: 0.2
  PDCD10:
    par: 0.13

#--------------------------------------------------------------------------------
# Variant specific options.  These over ride command line and config defaults.
#--------------------------------------------------------------------------------
variants:
  rs1064793348:
    max_rate: 0.5
  rs137853140:
    max_rate: 0.2
    CHROM: 7
    POS: 91855839
    REF: C
    ALT: T
    QUAL: 100
    FILTER: PASS
